_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "./output/t3_ft/model_final.pth"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t3_voc_coco_2007_ft', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: ()
  BASE_LR: 0.0001
  MAX_ITER: 2500
OUTPUT_DIR: "./output/t3_ft_baseline"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False