_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "./output/t3/model_final.pth"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ['t3_voc_coco_2007_train', 't1_voc_coco_2007_mixin_ft', 't2_voc_coco_2007_mixin_ft']
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: [13500]
  BASE_LR: 0.001
  MAX_ITER: 15000
OUTPUT_DIR: "./output/t3"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20