_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ['t1_voc_coco_2007_ft300', 't2_voc_coco_2007_ft300', 't3_voc_coco_2007_ft300']
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (8500, 8750)
  MAX_ITER: 9000
  WARMUP_ITERS: 10
OUTPUT_DIR: "./output/t3"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20  
  CLUSTERING:
    START_ITER: 100