_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t3_voc_coco_2007_ft', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (4500, 4750)
  MAX_ITER: 5000
  WARMUP_ITERS: 10
OUTPUT_DIR: "./output/t3"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20  
  CLUSTERING:
    START_ITER: 100