_BASE_: "./t1_train_fast.yaml"
DATASETS:
  TRAIN: ('t1_voc_coco_2007_mini_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test')   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (4500, 4825)
  MAX_ITER: 5000