_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t1_voc_coco_2007_ft300', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test',)   # voc_coco_2007_test, t1_voc_coco_2007_test, t1_voc_coco_2007_val
SOLVER:
  STEPS: (4500, 6000)
  MAX_ITER: 7500
  WARMUP_ITERS: 10
OUTPUT_DIR: "./output/t1"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 20
  CLUSTERING:
    START_ITER: 100
