_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "./output/t4_ft/model_final.pth"
DATASETS:
  TRAIN: ('t4_voc_coco_2007_ft', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: ()
  BASE_LR: 0.0001
  MAX_ITER: 4000
OUTPUT_DIR: "./output/t4_ft"
OWOD:
  PREV_INTRODUCED_CLS: 60
  CUR_INTRODUCED_CLS: 20
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
