_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t1_voc_coco_2007_train', 't2_voc_coco_2007_train', 't3_voc_coco_2007_train','t4_voc_coco_2007_train' )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (54000, 58000)
  MAX_ITER: 60000
  WARMUP_ITERS: 400
OUTPUT_DIR: "./output/t4"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 80
  CLUSTERING:
    START_ITER: 400