_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t4_voc_coco_2007_ft300', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (4500, 6000)
  MAX_ITER: 7500
  WARMUP_ITERS: 10
OUTPUT_DIR: "./output/t4"
OWOD:
  PREV_INTRODUCED_CLS: 60
  CUR_INTRODUCED_CLS: 20
  CLUSTERING:
    START_ITER: 100