_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
DATASETS:
  TRAIN: ('t1_voc_coco_2007_train', 't2_voc_coco_2007_train' ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (27000, 29000)
  MAX_ITER: 30000
  WARMUP_ITERS: 200
OUTPUT_DIR: "./output/t2"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 40
  CLUSTERING:
    START_ITER: 200