_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "./output/t2_ft/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_val_25', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('t2_voc_coco_2007_val_25', )
SOLVER:
  STEPS: (50000, 60000)
  MAX_ITER: 60
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_val"
OWOD:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
  ENABLE_CLUSTERING: False
  COMPUTE_ENERGY: True
  ENERGY_SAVE_PATH: 'energy'
  SKIP_TRAINING_WHILE_EVAL: False